name: test

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
          # - 'macos-latest'
          # - 'windows-latest'
        java-version:
          - "21"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to retrieve git tags
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: ${{ matrix.java-version }}
      - name: Run CI tests
        shell: bash
        run: |
          make ci-test
